token: "<< Your Token >>"

# Questions
questions:
  안녕:
    synonym: ["안녕하세요", "hi", "hello"]
    answer: "안녕하세요. CheckMate입니다."
    func: "say_hello(user)"

  요일:
    synonym: ["날짜", "오늘"]
    func: "get_day_of_week()"

  시간:
    synonym: [ "현재", "현재 시간", "now", "time" ]
    func: "get_time()"

  L/A 정산:
    synonym: ["L/A", "Learning Account", "Learning Account 정산", "러닝어카운트 정상", "러닝어카운트"]
    func: "get_la_info()"

  멤버:
    synonym: ["member", "우리", "우리 정보", "이메일", "email"]
    func: "get_member()"


